INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Bastide d´Izard', 'Armelle', 'Faire voyager l`étoile du berger et faire de l`amour un éloge de la sagesse.', 'Diplômée en ingénierie économique et financière, Armelle poursuit une carrière de directeur de production pendant 10 ans. Elle rencontre la peinture impressionniste tardivement et découvre sa vocation de peintre. Passionnée et appliquée, elle s`attèle à cette activité avec fougue et sérieux. Suivant les conseils d`experts, en parfaite autodidacte, elle fréquente assidument les musées pour s`initier et se former. Elle installe son atelier dans l`Hérault, entre vignobles et garrigues, dans sa maison familiale de Saint-Bauzille. L`artiste souhaite transmettre un message de paix, de sérénité et de spiritualité. Un état d`esprit qu`Armelle puise dans l`Hérault, un département magique aux décors parfaits à ses yeux. Très vite les professionnels repèrent son talent. Au hasard des rencontres, les galeries parisiennes lui ouvrent leurs portes. à présent Armelle est une artiste confirmée et sollicitée.', DATE '01-01-1968');
INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Rocco', 'Sophie', 'Les visages occupent l`espace et les couleurs de mes toiles et traduisent une vision et une douleur au monde, une souffrance muette.', 'Peintre et sculptrice contemporaine, Sophie Rocco débute une pratique picturale dès l`enfance. Autodidacte, elle réussi à quatorze ans le concours d`entrée en arts plastiques du collège Ganneron à Paris puis intègre l`école d`art graphique Sornas où elle apprend au contact de maitres, peintres réalistes contemporains qui l`initient au dessin et dont leur peinture va longtemps l`inspirer. à cela s`ajoute son amour inconditionnel pour la culture et les musées, enrichi par ses nombreux voyages aux quatre coins du monde, qui ont joué un rôle essentiel dans son épanouissement tant personnel qu`artistique. Imprégnée d`un sentiment profond d`isolement vis-à-vis du monde qui l`entoure, Sophie s`est patiemment construit une identité artistique et plastique résolument singulière, centrée sur l`exploration de l`âme humaine.', DATE '01-01-1945');
INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Kikayou', 'Kikayou', 'La puissance de l`imaginaire et des sentiments, rêves, souvenirs et travail sur l`inconscient me guident.', 'Né en 1966 dans le sud de la France, Kikayou s`est passionné très jeune pour le dessin, la peinture et la sculpture. Issu du graff et du tag, il a laissé sur la route, de ville en ville, des stigmates anonymes forgeant son univers. Des rencontres, des émotions puisées dans l`actualité et le quotidien ont fait le reste. Le monde qu`il s`est créé depuis le Pays Basque (où il vit avec sa grande famille) est à son image : fourmillant d`énergie et d`idées mais dénué de toute prétention. Il y peint entouré de sa famille et poursuit sa création de son univers fantaisiste en phase avec la conception de sa vie, et quelques ingrédients... le talent, l`imaginaire, les sentiments et la pertinence.', DATE '01-01-1966');
INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Desserle', 'Cecile', 'Une citation de Woody Allen : `Toi tu mets de l`art dans ton œuvre moi je mets de l’art dans ma vie`.', 'Après une double formation dévolue à l`apprentissage des Beaux-Arts et des Arts plastiques, Cécile débute sa carrière dans l`enseignement. Au travers de la transmission des techniques et savoirs culturels qu`elle dispense à ses élèves, la plasticienne avignonnaise commence, en parallèle, à développer sa propre production artistique. Profondément attachée à la notion de gestualité dans la pratique des arts plastiques, Cécile tourne rapidement son attention vers les œuvres issues de l`Action Painting, et tout particulièrement en direction des réalisations graphiques des artistes français Ernest PignonErnest (né en 1942) et Jacques Villéglé (né en 1926). La plasticienne va alors entamer l`écriture de son langage personnel en accordant une large place aux caractères typographiques dans la composition de ses œuvres, associée à une prédominance du geste dans leur réalisation. La volonté de capturer le mouvement sur la toile, de fixer à jamais tout ce qui se dérobe, tout ce qui est furtif, est une quête qui anime l`artiste depuis toujours, et qui ne cesse de s`affirmer au fil des années.', DATE '01-01-1971');
INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Lopez', 'Alfredo', 'Une couleur toute seule est orpheline. Ce qui est intéressant, c`est les rapports entre elles : un rouge et un noir ne racontent pas la même chose qu`un rouge et un vert.', 'D`origine Bolivienne, la famille déménage en Espagne où il passe son enfance. Son parcours professionnel varié l`amène à travailler dans des domaines allant du multimédia (infographie, web design) à l`illustration et la bande dessinée. A 36 ans, il échange son statut de créatif contre celui d’artiste et décide de se consacrer pleinement à sa passion : la peinture. Totalement inscrit dans notre époque, son travail puise ses racines dans notre quotidien. Alfredo célèbre en effet l`ordinaire. Son sujet d’étude : les occidentaux. La mythologie d`Alfredo représente la multitude d’actes sans importance accomplis dans la joie et la bonne humeur qui constituent notre vie. Ses œuvres sont des allégories de divers thèmes : le plaisir, le travail, le monde des affaires, l`amour, l’ivresse…', DATE '01-01-1964');
INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Garcia Gallardo', 'Mercedes', 'Les objets ont une âme que je fais émerger dans mes compositions. C`est le cœur qui me guide dès l`instant où je capte leur âme.', 'Mercedes grandit à Malaga et y commence ses études d`Arts. Quand elle part pour Barcelone, elle continue son apprentissage auprès d`artistes professionnels : Manolo Hugué (sculpture et émaillage) et Manuel Massana (dessin et peinture). Dans leur école, elle suit différents cours sur les techniques du vitrail, l`art primitif, la gravure, la symbolique du sacré et l`histoire de l`art. Elle se spécialise en art contemporain et décide de faire de sa passion son métier. En 2006, elle ouvre sa propre galerie à Cadaqués : l`Espace d`Art Gallardo. Le monde décrit dans ses peintures est un monde coloré et vivant qu`elle aborde frontalement avec des visages en gros plan (essentiellement des femmes) ou bien des paysages largement inspirés de son lieu de vie actuel (Cadaqués).', DATE '01-01-1960');
INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Medeya', 'Lemdiya', 'Une citation de Picasso : `Faut-il peindre ce qu`il y a sur un visage ? Ce qu`il y a dans un visage ? Ou ce qui se cache derrière un visage ?`', 'Medeya cultive deux passions depuis l`enfance : le sport et l`art. D`une nature résolument enthousiaste, touche à tout et proactive, elle exerce en tant que coach sportif durant plusieurs années , sans jamais cesser de créer en parallèle. En 2007, après une formation de tatouage, elle exerce ce métier passion à Casablanca durant quelques années tout en continuant son activité de coach sportif. Fin 2010, au retour de cinq années de vie passées à travailler à l`étranger, elle continue de perfectionner son dessin et suit des cours dans un atelier toulousain. Dans le même temps, elle décide d`inverser la tendance. Désormais, elle vivrait de son art et dédirait ses heures de loisirs à la pratique du sport.', DATE '01-01-1973');
INSERT INTO auteurs(auteur_nom_Auteurs, auteur_pnom_Auteurs, auteur_maxime_Auteurs, auteur_a_propos_Auteurs, auteur_datenai_Auteurs) VALUES('Villanueva Puigdelliura', 'Natalia', 'Ma démarche est de moderniser et de faire revivre la tradition de la peinture marine.', 'Pendant son enfance, Natalia fréquente deux voisins, un céramiste et un peintre, qui lui font découvrir l’art. Elle ressent à son tour le désir de créer de ses mains autant qu’au pinceau. Elle grandit sur la Côte Catalane et s’imprègne fortement de l’atmosphère marine. Passionnée par ces paysages, elle part à la rencontre d’autres pays de bord de mer (Maroc, Sénégal, Italie, Espagne). Au contact des ports de pêche, des marins et des phares solitaires, elle trouve une force et une inspiration pour sa peinture. Parallèlement, elle se passionne pour les œuvres marines de l’artiste Juan Abello qu’elle rencontre. Naturellement, elle s’oriente vers une formation de céramiste à l’Ecole Industrielle de Barcelone. Elle complète sa formation par des cours de dessin, de peinture et de gravure. De cette double expérience, elle conserve le goût du toucher des matières d’une part et le plaisir du dessin d’autre part.', DATE '01-01-1975');

INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('La maison de Dali … La résistance en riant', 'Cette oeuvre d`art contemporain unique et originale `La maison de Dali … La résistance en riant` a été réalisée par l`artiste contemporain Bastide d´Izard Armelle.L`artiste a utilisé la technique Huile pour créer cette peinture grand format sur toile de style Abstrait sur le thème Paysages.', 100, 100, 2700, true, 1);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Paix sur le monde', 'Cette oeuvre d`art contemporain unique et originale `Paix sur le monde` a été réalisée par l`artiste contemporain Bastide d´Izard Armelle.L`artiste a utilisé la technique Acrylique pour créer cette peinture grand format sur toile de style Abstrait sur le thème Paysages.', 100, 100, 2700, true, 1);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Paix sur le monde II', 'Cette oeuvre d`art contemporain unique et originale `Paix sur le monde` a été réalisée par l`artiste contemporain Bastide d´Izard Armelle.L`artiste a utilisé la technique Acrylique pour créer cette peinture grand format sur toile de style Abstrait sur le thème Paysages.', 100, 100, 2700, false, 1);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Matin magique', 'Cette oeuvre d`art contemporain unique et originale `F2 No Name 109-1121-20220906-6` a été réalisée par l`artiste contemporain Bastide d´Izard Armelle.L`artiste a utilisé la technique Huile pour créer cette peinture petit format sur toile de style Abstrait.', 19, 19, 155, false, 1); 
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Matin magique II', 'Cette oeuvre d`art contemporain unique et originale `F2 No Name 109-1121-20220906-6` a été réalisée par l`artiste contemporain Bastide d´Izard Armelle.L`artiste a utilisé la technique Huile pour créer cette peinture petit format sur toile de style Abstrait.', 19, 19, 155, false, 1); 
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Matin magique III', 'Cette oeuvre d`art contemporain unique et originale `F2 No Name 109-1121-20220906-6` a été réalisée par l`artiste contemporain Bastide d´Izard Armelle.L`artiste a utilisé la technique Huile pour créer cette peinture petit format sur toile de style Abstrait.', 19, 19, 155, false, 1);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Une nuit a la mer', 'Cette oeuvre d`art contemporain unique et originale `Une nuit a la mer` a été réalisée par l`artiste contemporain Rocco Sophie.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur toile de style Figuratif sur le thème Paysages.', 100, 100, 2700, true, 2);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Snoopy surfing', 'Cette oeuvre d`art contemporain unique et originale `Snoopy surfing` a été réalisée par l`artiste contemporain Kikayou.L`artiste a utilisé les techniques Acrylique, Graffiti, Mixte pour créer cette peinture grand format sur toile de style Street Art sur les thèmes icones Pop, scènes de vie.', 100, 100, 2700, true, 8);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Minnie surf', 'Cette oeuvre d`art contemporain unique et originale `F4 No Name 101-20342-20220909-6` a été réalisée par l`artiste contemporain Kikayou.L`artiste a utilisé la technique Mixte pour créer cette peinture petit format sur toile de style Pop Art sur le thème icones Pop.', 36, 36, 460, false, 8); 
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Brûler d`amour', 'Cette oeuvre d`art contemporain unique et originale `Brûler d`amour` a été réalisée par l`artiste contemporain Desserle Cecile.L`artiste a utilisé la technique Huile pour créer cette peinture grand format sur toile de style Figuratif sur le thème Portraits.', 100, 100, 3400, true, 7);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('papa voudrait un moment à lui', 'Cette oeuvre d`art contemporain unique et originale `papa voudrait un moment à lui` a été réalisée par l`artiste contemporain Lopez Alfredo.L`artiste a utilisé la technique Acrylique pour créer cette peinture grand format sur toile de style Illustration sur le thème scènes de vie.', 100, 100, 2700, false, 3); 
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('La tarde', 'Cette oeuvre d`art contemporain unique et originale `La tarde` a été réalisée par l`artiste contemporain Garcia Gallardo Mercedes.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur papier de style Art Singulier sur le thème scènes de vie.', 100, 100, 2700, false, 4); 
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('La tarde II', 'Cette oeuvre d`art contemporain unique et originale `La tarde` a été réalisée par l`artiste contemporain Garcia Gallardo Mercedes.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur papier de style Art Singulier sur le thème scènes de vie.', 100, 100, 2700, true, 4);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('La tarde III', 'Cette oeuvre d`art contemporain unique et originale `La tarde` a été réalisée par l`artiste contemporain Garcia Gallardo Mercedes.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur papier de style Art Singulier sur le thème scènes de vie.', 100, 100, 2700, false, 4);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('L`amour est dans le verre', 'Cette oeuvre d`art contemporain unique et originale `L`amour est dans le verre` a été réalisée par l`artiste contemporain Lopez Alfredo.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur toile de style Surréaliste sur le thème scènes de vie.', 100, 100, 2700, true, 3);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('La vierge de Sassoferato et son rubik`s cube', 'Cette oeuvre d`art contemporain unique et originale `La vierge de Sassoferato et son rubik`s cube` a été réalisée par l`artiste contemporain Medeya Lemdiya.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur métal de style Pop Art sur le thème icones Pop.', 100, 100, 2700, false, 5); 
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('La vierge de Sassoferato et son rubik`s cube II', 'Cette oeuvre d`art contemporain unique et originale `La vierge de Sassoferato et son rubik`s cube` a été réalisée par l`artiste contemporain Medeya Lemdiya.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur métal de style Pop Art sur le thème icones Pop.', 100, 100, 2700, true, 5);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Harley Quinn', 'Cette oeuvre d`art contemporain unique et originale `Harley Quinn` a été réalisée par l`artiste contemporain Medeya Lemdiya.L`artiste a utilisé la technique Mixte pour créer cette peinture petit format sur métal de style Pop Art sur le thème icones Pop.', 13, 13, 105, false, 5);
INSERT INTO oeuvres(oeuvre_titre_Oeuvres, oeuvre_descrip_Oeuvres, oeuvre_dim_larg_Oeuvres, oeuvre_dim_haut_Oeuvres, prix_TTC_Oeuvres, en_stock_Oeuvres, auteur_id_Auteurs) VALUES('Bodega', 'Cette oeuvre d`art contemporain unique et originale `Bodega` a été réalisée par l`artiste contemporain Villanueva Puigdelliura Natalia.L`artiste a utilisé la technique Mixte pour créer cette peinture grand format sur toile de style Figuratif sur le thème natures mortes.', 100, 100, 2700, true, 6);


INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Guarim', 'Raphael', 'CROUS 👉', 62100, 'Calais', 'raphaguarim@gmail.com', 615, 2);
INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Watel', 'Noa', '5 Place Henri Henneguelle', 62200, 'Boulogne', 'noa.watel@gmail.com', 0, 0);
INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Melebe', 'Mayel', '1453 Avenue Charles de Gaulle', 62231, 'Coquelles', 'corneilmalebe@gmail.com', 155, 1);
INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Berdin', 'Clement', '322 rue Jacob', 62610, 'Balinghem', 'clement.melisse@gmail.com', 8100, 3);
INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Biscaras', 'Pierre', '988 rue du petit Courgain', 62100, 'Calais', 'pierre.biscaras@orange.fr', 5660, 4);
INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Caron', 'Samuel', '21 Contour du Sud', 59430, 'Fort Mardyck', 'samuelcarondu9@gmail.com', 0, 0);
INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Gambert', 'Adrien', '9 allée des Primevères', 62250, 'Marquise', 'gambertad@gmail.com', 0, 0);
INSERT INTO clients(cli_nom_Clients, cli_pnom_Clients, cli_adr_Clients, cli_cp_Clients, cli_ville_Clients, cli_mail_Clients, cli_ca_Clients, cli_nb_oeuvres_Clients) VALUES('Tetart', 'Julian', '20 Rue d`Alembert', 62100, 'Calais', 'julian.tetart02@gmail.com', 0, 0);

INSERT INTO factures(date_fac_Factures, cli_id_Clients, montant_ttc_Factures, fac_nb_oeuvre_Factures) VALUES(DATE '12-01-2021', 1, 615, 2);
INSERT INTO factures(date_fac_Factures, cli_id_Clients, montant_ttc_Factures, fac_nb_oeuvre_Factures) VALUES(DATE '01-13-2021', 3, 155, 1);
INSERT INTO factures(date_fac_Factures, cli_id_Clients, montant_ttc_Factures, fac_nb_oeuvre_Factures) VALUES(DATE '06-27-1989', 4, 2700, 1);
INSERT INTO factures(date_fac_Factures, cli_id_Clients, montant_ttc_Factures, fac_nb_oeuvre_Factures) VALUES(DATE '04-12-2002', 4, 5400, 2);
INSERT INTO factures(date_fac_Factures, cli_id_Clients, montant_ttc_Factures, fac_nb_oeuvre_Factures) VALUES(DATE '06-12-2022', 5, 5660, 4);

INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(9, 1);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(4, 1);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(5, 4);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(14, 5);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(12, 2);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(11, 2);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(3, 3);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(6, 3);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(16,3);
INSERT INTO ventes(oeuvre_id_Oeuvres, fac_id_Factures) VALUES(18, 3);